import createClient from "openapi-fetch";
// This file will be generated by the `deno task generate-client` command hitting the Java backend.
// We provide a fallback interface during initial development if the file hasn't been generated yet.
import type { paths } from "./api-schema.d.ts";

/**
 * Type-safe apiClient constructed from the OpenLiberty/Quarkus MicroProfile OpenAPI endpoint.
 *
 * Notice that the baseUrl targets the standard React proxy address -> `/api`,
 * not the direct java backend port (`http://localhost:9080`).
 * The Deno edge server (`server.tsx`) will securely intercept these calls and proxy them.
 */
export const apiClient = createClient<paths>({
  baseUrl: "/api",
  headers: {
    "Accept": "application/json",
  }
});

/**
 * You can also intercept requests for things like Auth tokens if you don't
 * store it simply in an HTTP-Only cookie.
 *
 * apiClient.use({
 *   onRequest: (req) => {
 *      req.headers.set("Authorization", `Bearer ${localStorage.getItem("token")}`);
 *      return req;
 *   }
 * });
 */

