mp.openapi.scan.packages=core.calculations,core.execution_rules,core.feeds,core.order_matching,core.portfolio_tracking,core.simulation,core.volatility
mp.openapi.scan.exclude.classes=core.api.SimpleOpenApiResource,core.api.SwaggerUiResource

